apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gophish
  template:
    metadata:
      labels:
        app: gophish
    spec:
      containers:
      - name: gophish
        image: gophish/gophish
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: gophish
spec:
  type: NodePort
  ports:
  - port: 3333
    nodePort: 30002
  selector:
    app: gophish
