apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-juiceshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owasp-juiceshop
  template:
    metadata:
      labels:
        app: owasp-juiceshop
    spec:
      containers:
      - name: owasp-juiceshop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: owasp-juiceshop
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
  selector:
    app: owasp-juiceshop
